name: rag_chatbot
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.9.18
  - pip=22.3.1
  - openai=1.3.5
  - langchain=0.0.335
  - chromadb=0.4.18
  - streamlit=1.28.0
  - docx2txt=0.8
  - pypdf=3.17.0
  - pdfminer.six=20221105
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - pandas=2.0.3
  - networkx=3.1
  - jupyter=1.0.0
  - notebook=6.5.5
  - pip:
    # Newer langchain packages not yet in conda-forge
    - langchain-openai==0.0.2
    - langchain-community==0.0.13
    - langchain-text-splitters==0.0.1
    - langchain-core==0.1.0
    - langchain-chroma==0.0.1
    
    # Unstructured packages (complex dependencies)
    - unstructured==0.10.30
    - unstructured-inference==0.7.13